-- ─────────────────────────────────────────────────────────────────────────────
-- Workout Tables
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Table relationships:
--   workout_sessions
--     └── workout_exercise_logs (many per session, ordered by exercise_order)
--           └── workout_sets (many per log, ordered by set_number)
--
-- Exercise definitions live in the mobile fixture (workoutFixtures.ts).
-- Only exercise_id (string) is stored here.
--
-- Session IDs are generated client-side (UUID). Exercise log and set IDs
-- are generated by the database.

-- ─────────────────────────────────────────────────────────────────────────────
-- Tables
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE workout_sessions (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  duration_seconds INT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE workout_exercise_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES workout_sessions(id) ON DELETE CASCADE,
  exercise_id TEXT NOT NULL,
  exercise_order INT NOT NULL,
  notes TEXT
);

CREATE TABLE workout_sets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  log_id UUID NOT NULL REFERENCES workout_exercise_logs(id) ON DELETE CASCADE,
  set_number INT NOT NULL,
  reps INT,
  weight_kg NUMERIC(6,2),
  duration_seconds INT,
  rpe NUMERIC(3,1),
  completed_at TIMESTAMPTZ NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- Service role key bypasses RLS, but these policies add defence-in-depth
-- for any direct Supabase client access.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE workout_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_exercise_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_sets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users own sessions"
  ON workout_sessions FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "users own exercise logs"
  ON workout_exercise_logs FOR ALL
  USING (
    session_id IN (
      SELECT id FROM workout_sessions WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "users own sets"
  ON workout_sets FOR ALL
  USING (
    log_id IN (
      SELECT wel.id
      FROM workout_exercise_logs wel
      JOIN workout_sessions ws ON ws.id = wel.session_id
      WHERE ws.user_id = auth.uid()
    )
  );

-- ─────────────────────────────────────────────────────────────────────────────
-- Indexes
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX idx_workout_sessions_user_date
  ON workout_sessions(user_id, date DESC);

CREATE INDEX idx_workout_exercise_logs_session
  ON workout_exercise_logs(session_id, exercise_order);

CREATE INDEX idx_workout_sets_log
  ON workout_sets(log_id, set_number);

-- ─────────────────────────────────────────────────────────────────────────────
-- updated_at trigger
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER workout_sessions_updated_at
  BEFORE UPDATE ON workout_sessions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
